

export const PROMOTION_PRODUCT_LIST_REQUEST = "PROMOTION_PRODUCT_LIST_REQUEST";
export const PROMOTION_PRODUCT_LIST_SUCCESS = "PROMOTION_PRODUCT_LIST_SUCCESS";
export const PROMOTION_PRODUCT_LIST_FAIL = "PROMOTION_PRODUCT_LIST_FAIL";
export const PROMOTION_PRODUCT_LIST_RESET = "PROMOTION_PRODUCT_LIST_RESET";
